"""initial schema

Revision ID: 1058a5a30e8f
Revises: 
Create Date: 2026-02-22 20:58:36.629223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1058a5a30e8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('TEXTILE', 'JEWELLERY', 'TOY', 'CANDLE', 'COSMETIC', 'CERAMIC', 'WOOD', 'PAPER', 'OTHER', name='productcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('responsible_persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('logo_data', sa.Text(), nullable=True),
    sa.Column('is_self', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('responsible_person_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('batch_code', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RELEASED', 'SUPERSEDED', 'RECALLED', name='versionstatus'), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('intended_use', sa.Text(), nullable=False),
    sa.Column('foreseeable_misuse', sa.Text(), nullable=True),
    sa.Column('target_consumers', sa.String(length=255), nullable=True),
    sa.Column('applied_standards', sa.Text(), nullable=True),
    sa.Column('declaration_of_conformity_path', sa.String(length=500), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('retention_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['product_families.id'], ),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['responsible_persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'version_number', name='uq_family_version')
    )
    op.create_table('bill_of_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_version_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('material_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('origin_country', sa.String(length=100), nullable=True),
    sa.Column('certificate_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_version_id', sa.UUID(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_serious', sa.Boolean(), nullable=True),
    sa.Column('authority_notified', sa.Boolean(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_version_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('TECHNICAL_FILE', 'LABEL_PRINT', 'AMAZON_IMAGE', 'AMAZON_TEXT', 'DECLARATION_CONFORMITY', name='documenttype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_version_id', sa.UUID(), nullable=False),
    sa.Column('hazard_type', sa.Enum('PHYSICAL', 'CHEMICAL', 'THERMAL', 'ELECTRICAL', 'BIOLOGICAL', 'MECHANICAL', 'OTHER', name='hazardtype'), nullable=False),
    sa.Column('hazard_description', sa.Text(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('mitigation_measure', sa.Text(), nullable=False),
    sa.Column('safety_warning_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_assessments')
    op.drop_table('generated_documents')
    op.drop_table('complaints')
    op.drop_table('bill_of_materials')
    op.drop_table('product_versions')
    op.drop_table('suppliers')
    op.drop_table('responsible_persons')
    op.drop_table('product_families')
    # ### end Alembic commands ###
